[[pages]]
path = "pages/1_overview.py"
name = "Overview"
icon = "âš™ï¸"
url_path = "overview"

[[pages]]
path = "pages/2_requester_detail.py"
name = "Requester & Approver"
icon = "ğŸ¤"
url_path = "requester-approver-detail"

[[pages]]
path = "pages/3_mdm_detail.py"
name = "Master Data Management"
icon = "ğŸ“¶"
url_path = "mdm-detail"